// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartParking.Infrastructure.Persistence;

#nullable disable

namespace SmartParking.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260613213200_UpdateSlotStatusHistoryForPhase4")]
    partial class UpdateSlotStatusHistoryForPhase4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartParking.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<byte>("ActionType")
                        .HasColumnType("tinyint")
                        .HasColumnName("action_type");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("entity_name");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_values");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("timestamp");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ActionType")
                        .HasDatabaseName("idx_audit_logs_action_type");

                    b.HasIndex("EntityName")
                        .HasDatabaseName("idx_audit_logs_entity_name");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("idx_audit_logs_timestamp");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_audit_logs_user_id");

                    b.HasIndex("EntityName", "EntityId")
                        .HasDatabaseName("idx_audit_logs_entity");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("message");

                    b.Property<byte>("NotificationType")
                        .HasColumnType("tinyint")
                        .HasColumnName("notification_type");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("read_at");

                    b.Property<string>("RelatedEntityId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("related_entity_id");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("related_entity_type");

                    b.Property<byte>("Severity")
                        .HasColumnType("tinyint")
                        .HasColumnName("severity");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_notifications_created_at");

                    b.HasIndex("IsArchived")
                        .HasDatabaseName("idx_notifications_is_archived");

                    b.HasIndex("IsRead")
                        .HasDatabaseName("idx_notifications_is_read");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_notifications_user_id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.ParkingArea", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("TotalCapacity")
                        .HasColumnType("int")
                        .HasColumnName("total_capacity");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("idx_parking_areas_is_deleted");

                    b.ToTable("parking_areas", (string)null);
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.ParkingIncident", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<byte>("IncidentType")
                        .HasColumnType("tinyint")
                        .HasColumnName("incident_type");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ParkingAreaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parking_area_id");

                    b.Property<DateTime>("ReportedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("reported_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("ReportedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("reported_by");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("resolution_notes");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("resolved_by");

                    b.Property<byte>("Severity")
                        .HasColumnType("tinyint")
                        .HasColumnName("severity");

                    b.Property<Guid?>("SlotId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("slot_id");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("ZoneId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("zone_id");

                    b.HasKey("Id");

                    b.HasIndex("ParkingAreaId")
                        .HasDatabaseName("idx_incidents_parking_area_id");

                    b.HasIndex("ReportedAt")
                        .HasDatabaseName("idx_incidents_reported_at");

                    b.HasIndex("ReportedBy");

                    b.HasIndex("ResolvedBy");

                    b.HasIndex("Severity")
                        .HasDatabaseName("idx_incidents_severity");

                    b.HasIndex("SlotId")
                        .HasDatabaseName("idx_incidents_slot_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_incidents_status");

                    b.HasIndex("ZoneId")
                        .HasDatabaseName("idx_incidents_zone_id");

                    b.ToTable("parking_incidents", (string)null);
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.ParkingSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("created_by");

                    b.Property<byte>("CurrentStatus")
                        .HasColumnType("tinyint")
                        .HasColumnName("current_status");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSensorEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_sensor_enabled");

                    b.Property<DateTime>("LastStatusChange")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("last_status_change")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("SlotNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("slot_number");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<byte>("VehicleType")
                        .HasColumnType("tinyint")
                        .HasColumnName("vehicle_type");

                    b.Property<decimal>("XCoordinate")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("x_coordinate");

                    b.Property<decimal>("YCoordinate")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("y_coordinate");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("zone_id");

                    b.HasKey("Id");

                    b.HasIndex("CurrentStatus")
                        .HasDatabaseName("idx_slots_current_status");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("idx_slots_is_deleted");

                    b.HasIndex("SlotNumber")
                        .IsUnique()
                        .HasDatabaseName("idx_slots_slot_number");

                    b.HasIndex("VehicleType")
                        .HasDatabaseName("idx_slots_vehicle_type");

                    b.HasIndex("ZoneId")
                        .HasDatabaseName("idx_slots_zone_id");

                    b.ToTable("parking_slots", (string)null);
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.PredictionSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CalculationBasis")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("calculation_basis");

                    b.Property<byte>("ConfidenceLevel")
                        .HasColumnType("tinyint")
                        .HasColumnName("confidence_level");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("ForecastTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("forecast_time");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("ParkingAreaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parking_area_id");

                    b.Property<int>("PredictedOccupancyCount")
                        .HasColumnType("int")
                        .HasColumnName("predicted_occupancy_count");

                    b.Property<decimal>("PredictedOccupancyPercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("predicted_occupancy_percentage");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<byte>("VehicleType")
                        .HasColumnType("tinyint")
                        .HasColumnName("vehicle_type");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("zone_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_prediction_snapshots_created_at");

                    b.HasIndex("ForecastTime")
                        .HasDatabaseName("idx_prediction_snapshots_forecast_time");

                    b.HasIndex("ParkingAreaId")
                        .HasDatabaseName("idx_prediction_snapshots_parking_area_id");

                    b.HasIndex("ZoneId")
                        .HasDatabaseName("idx_prediction_snapshots_zone_id");

                    b.ToTable("prediction_snapshots", (string)null);
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("expiry_date");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiryDate")
                        .HasDatabaseName("idx_refresh_tokens_expiry")
                        .HasFilter("[is_revoked] = 0");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("idx_refresh_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.SlotStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("changed_at");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("changed_by_user_id");

                    b.Property<byte>("NewStatus")
                        .HasColumnType("tinyint")
                        .HasColumnName("new_status");

                    b.Property<byte>("PreviousStatus")
                        .HasColumnType("tinyint")
                        .HasColumnName("previous_status");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("SlotId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("slot_id");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt")
                        .HasDatabaseName("idx_slot_status_history_changed_at");

                    b.HasIndex("ChangedByUserId")
                        .HasDatabaseName("idx_slot_status_history_changed_by_user_id");

                    b.HasIndex("NewStatus")
                        .HasDatabaseName("idx_slot_status_history_new_status");

                    b.HasIndex("SlotId")
                        .HasDatabaseName("idx_slot_status_history_slot_id");

                    b.ToTable("slot_status_history", (string)null);
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("setting_key");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("setting_value");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SettingKey")
                        .IsUnique()
                        .HasDatabaseName("idx_system_settings_key");

                    b.ToTable("system_settings", (string)null);
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("password_hash");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_users_email");

                    b.HasIndex("Role")
                        .HasDatabaseName("idx_users_role");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("idx_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("MapColorHex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("map_color_hex");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<Guid>("ParkingAreaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parking_area_id");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("idx_zones_is_deleted");

                    b.HasIndex("ParkingAreaId")
                        .HasDatabaseName("idx_zones_parking_area_id");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("idx_zones_sort_order");

                    b.ToTable("zones", (string)null);
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("SmartParking.Domain.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.Notification", b =>
                {
                    b.HasOne("SmartParking.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.ParkingIncident", b =>
                {
                    b.HasOne("SmartParking.Domain.Entities.ParkingArea", "ParkingArea")
                        .WithMany()
                        .HasForeignKey("ParkingAreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartParking.Domain.Entities.User", "Reporter")
                        .WithMany("ReportedIncidents")
                        .HasForeignKey("ReportedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartParking.Domain.Entities.User", "Resolver")
                        .WithMany("ResolvedIncidents")
                        .HasForeignKey("ResolvedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartParking.Domain.Entities.ParkingSlot", "Slot")
                        .WithMany()
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartParking.Domain.Entities.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParkingArea");

                    b.Navigation("Reporter");

                    b.Navigation("Resolver");

                    b.Navigation("Slot");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.ParkingSlot", b =>
                {
                    b.HasOne("SmartParking.Domain.Entities.Zone", "Zone")
                        .WithMany("ParkingSlots")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.PredictionSnapshot", b =>
                {
                    b.HasOne("SmartParking.Domain.Entities.ParkingArea", "ParkingArea")
                        .WithMany("PredictionSnapshots")
                        .HasForeignKey("ParkingAreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartParking.Domain.Entities.Zone", "Zone")
                        .WithMany("PredictionSnapshots")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParkingArea");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("SmartParking.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.SlotStatusHistory", b =>
                {
                    b.HasOne("SmartParking.Domain.Entities.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartParking.Domain.Entities.ParkingSlot", "Slot")
                        .WithMany("StatusHistory")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.Zone", b =>
                {
                    b.HasOne("SmartParking.Domain.Entities.ParkingArea", "ParkingArea")
                        .WithMany("Zones")
                        .HasForeignKey("ParkingAreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParkingArea");
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.ParkingArea", b =>
                {
                    b.Navigation("PredictionSnapshots");

                    b.Navigation("Zones");
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.ParkingSlot", b =>
                {
                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Notifications");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ReportedIncidents");

                    b.Navigation("ResolvedIncidents");
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.Zone", b =>
                {
                    b.Navigation("ParkingSlots");

                    b.Navigation("PredictionSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
